http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline

pipeline:
  workers: ${NUM_WORKERS:1}
  batch:
    # The maximum number of events an individual worker thread
    # will collect from inputs before attempting to execute
    # its filters and outputs.
    size: ${BATCH_SIZE:50}
