http.host: "0.0.0.0"

pipeline:
  batch:
    # The maximum number of events an individual worker thread
    # will collect from inputs before attempting to execute
    # its filters and outputs.
    size: 50
