http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline

pipeline:
  batch:
    # The maximum number of events an individual worker thread
    # will collect from inputs before attempting to execute
    # its filters and outputs.
    size: 10

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.url: $ELASTICSEARCH_URL
